mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:9090
secret: 6d77322a-2a9b-4c4f-bd96-23246d9362a3
log-level: info
ipv6: true
mode: rule
hosts:
  '*.test': 127.0.0.1
profile:
  tracing: true

proxies:
  - name: "s1"
    type: ss
    server:
    port:
    cipher: aes-256-gcm
    password: ""
    udp: true

  - name: "s2"
    type: "vmess"
    server:
    port:
    uuid:
    alterId: 0
    cipher: auto
    udp: false

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - s1
      - s2

  - name: "BALANCE"
    type: load-balance
    strategy: consistent-hashing
    interval: 10
    url: "http://cp.cloudflare.com/generate_204"
    proxies:
      - s1
      - s2

rule-providers:
  tsui:
    type: http
    behavior: classical
    interval: 10
    format: yaml
    size-limit: 0
    url: 'https://hub.gitmirror.com/https://raw.githubusercontent.com/cuiqg/settings/refs/heads/main/clash/rulesets/tsui.yaml'
    path: ./rulesets/tsui.yaml

rules:
  - GEOSITE,gfw,PROXY
  - GEOIP,telegram,PROXY
  - RULE-SET,tsui,BALANCE
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,DIRECT
