mixed-port: 7890
allow-lan: false
external-controller: 127.0.0.1:9090
secret: 6d77322a-2a9b-4c4f-bd96-23246d9362a3
log-level: info
ipv6: true
mode: rule
hosts:
  '*.test': 127.0.0.1
profile:
  tracing: true
  store-selected: true
  store-fake-ip: true

geox-url:
  geoip: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdmirror.com/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: true
geo-update-interval: 24

dns:
  enable: true
  cache-algorithm: arc
  ipv6: true
  default-nameserver:
    - 94.140.14.14
    - 94.140.15.15
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
    - 1.1.1.1
    - 1.0.0.1

proxies:
  - name: "s1"
    type: ss
    server:
    port:
    cipher: aes-256-gcm
    password: ""
    udp: true

  - name: "s2"
    type: "vmess"
    server:
    port:
    uuid:
    alterId: 0
    cipher: auto
    udp: false

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - s1
      - s2

  - name: "BALANCE"
    type: load-balance
    strategy: consistent-hashing
    interval: 10
    url: "http://cp.cloudflare.com/generate_204"
    proxies:
      - s1
      - s2

rule-providers:
  tsui:
    type: http
    behavior: classical
    interval: 10
    format: yaml
    size-limit: 0
    url: "https://cdn.jsdmirror.com/gh/cuiqg/settings/clash/rulesets/tsui.yaml"
    path: ./rulesets/tsui.yaml

rules:
  - GEOSITE,gfw,PROXY
  - GEOIP,telegram,PROXY
  - RULE-SET,tsui,BALANCE
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,DIRECT
